// Generated by https://quicktype.io

export interface PokemonFullName {
   count:    number;
   next:     string;
   previous: null;
   results:  Resulta[];
}

export interface Resulta {
   name: string;
   url:  string;
}
